openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http'
paths:
  /cakes:
    get:
      description: return list of all available cakes
      responses:
        200:
          description: server is ok
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#components/schemas/cakes'

  /cake/{id}:
    get:
      description: return cake with id
      responses:
        200:
          description: is ok
          content:
            application/json:
              schema:
                $ref: '#components/schemas/cake'
        404:
          description: not found

  /addCake:
    post:
      responses:
        200:
          description: is ok
          content:
            application/json:
             schema:
              $ref: '#components/schemas/cake'


  /addorder:
    post:
      responses:
        200:
          description: is ok
          content:
            application/json:
              schema:
                $ref: '#components/schemas/order'

  /adduser:
    post:
      responses:
        200:
          description: is ok
          content:
            application/json:
              schema:
                $ref: '#components/schemas/user'




components:
  schemas:
    cakes:
      additionalProperties: false
      type: object
      properties:
        cake_list:
          type: array
          items:
            $ref: '#/components/schemas/cake'

    cake:
      type: object
      description: Short info about cakes
      required:
        - name
        - calories
        - image
        - price
        - weight
        - id
      properties:
        id:
          type: number
          description: Id of cake
        name:
          type: string
          description: Name of cake
        calories:
          type: number
          description: calories of cake
        image:
          type: string
          description: relative url of cake image
        price:
          type: number
          description: Prise of cake
        weight:
          type: number
          description: Cake weight

    user:
      type: object
      required:
        - name
        - number
      properties:
        number:
          type: string
          description: number
        name:
          type: string
          description: name

    purchase:
      type: object
      required:
        - id
        - number
      properties:
        number:
          type: integer
          description: id
        name:
          type: integer
          description: number

    order:
      type: object
      required:
        - delivery
        - deliverytime
        - deliveryaddress
        - orderstatus
        - payment
        - purhases
        - user
      properties:
        user:
          $ref: '#/components/schemas/user'
        delivery:
          type: string
          description: do you need delivery
          enum:
            - NEED
            - NO
        deliveryaddress:
          type: string
          description: deliveryaddress
        deliverytime:
          type: string
          description: deliverytime
          format: date-time
        payment:
          type: string
          description: payment status
          enum:
            - ONLINE
            - OFFLINE
        orderstatus:
          type: string
          description: orderstatus
          enum:
            - NEW
            - CANCELED
            - PERFORMED
            - FINISHED
        purhases:
          type: array
          description: purchases
          items:
            $ref: '#/components/schemas/purchase'



  
